#use_frameworks!
platform:ios, '7.0'

target 'MJSDK-cocoapods_Example' do
  pod 'MJSDK-cocoapods', :path => '../'

  target 'MJSDK-cocoapods_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'

pod 'AFNetworking'
pod 'Masonry'
pod 'Mantle'
pod 'OpenSSL'
#pod 'SVProgressHUD'
pod 'MBProgressHUD'
pod 'SSKeychain'
pod 'ReactiveCocoa', '~>2.0'

  end
end
